<a href="https://colab.research.google.com/github/SONY-PS/DS-Lab/blob/main/experiment1B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
print(x.shape)

(4,)


In [8]:
y=np.array([[1,2],[3,4]])

In [9]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [11]:
z=np.array([[1+0.j,2+5.j]])

In [12]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [13]:
a=np.zeros((2,3))

In [14]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(a.shape)

(2, 3)


In [16]:
b=np.ones((2,3),dtype=int)

In [18]:
print(b)

[[1 1 1]
 [1 1 1]]


In [19]:
d=np.eye(3)

In [20]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
e=np.arange(10)

In [22]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
e=np.arange(12,21)

In [24]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [25]:
e=np.arange(5,20,3)
print(e)

[ 5  8 11 14 17]


In [27]:
f=np.linspace(1,20,7)
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [28]:
g=np.random.random((3,4))
print(g)

[[0.95181214 0.09495752 0.9582814  0.12032283]
 [0.79002974 0.40959734 0.82257612 0.11601148]
 [0.47824931 0.0536245  0.32043238 0.81271435]]


In [29]:
h=np.random.random((3,4))
print(h.reshape(2,2,3))

[[[0.18041498 0.193619   0.44146511]
  [0.16051881 0.23459966 0.2154995 ]]

 [[0.9059489  0.51983242 0.02147413]
  [0.28766391 0.8035354  0.62766828]]]


In [30]:
x=np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [32]:
print(x[-1])
x.resize(3,4)
print(x)

11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
print(x[-1,-1])

11


In [35]:
print(x[2][3])

11


In [36]:
y=np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [37]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [38]:
print(y[10:15])

[11 12 13 14 15]


In [39]:
print(y[-5:])

[21 22 23 24 25]


In [40]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [41]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [42]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [43]:
y=y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [44]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [45]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [46]:
print(y[:,-1])

[ 5 10 15 20 25]


In [47]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [48]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [50]:
a=np.arange(1,6)
b=np.arange(6,11)

In [51]:
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [ ]:
print(a>3)

In [52]:
a=np.arange(0,4).reshape((2,2))
b=np.eye(2)

In [53]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [54]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [55]:
x=np.arange(1,10).reshape(3,3)

In [56]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
print(x.sum())

45


In [58]:
print(x.sum(axis=0))

[12 15 18]


In [59]:
x=np.arange(1,19).reshape(3,3,2)

In [60]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [63]:
x=np.arange(1,10).reshape(3,3)
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [64]:
print(x.max(axis=0))

[7 8 9]


In [65]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
